package com.espressif.iot.db.greenrobot.daoDevice;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.espressif.iot.db.greenrobot.daoDevice.UserDB;
import com.espressif.iot.db.greenrobot.daoDevice.DeviceDB;
import com.espressif.iot.db.greenrobot.daoDevice.user__device;

import com.espressif.iot.db.greenrobot.daoDevice.UserDBDao;
import com.espressif.iot.db.greenrobot.daoDevice.DeviceDBDao;
import com.espressif.iot.db.greenrobot.daoDevice.user__deviceDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig userDBDaoConfig;
    private final DaoConfig deviceDBDaoConfig;
    private final DaoConfig user__deviceDaoConfig;

    private final UserDBDao userDBDao;
    private final DeviceDBDao deviceDBDao;
    private final user__deviceDao user__deviceDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        userDBDaoConfig = daoConfigMap.get(UserDBDao.class).clone();
        userDBDaoConfig.initIdentityScope(type);

        deviceDBDaoConfig = daoConfigMap.get(DeviceDBDao.class).clone();
        deviceDBDaoConfig.initIdentityScope(type);

        user__deviceDaoConfig = daoConfigMap.get(user__deviceDao.class).clone();
        user__deviceDaoConfig.initIdentityScope(type);

        userDBDao = new UserDBDao(userDBDaoConfig, this);
        deviceDBDao = new DeviceDBDao(deviceDBDaoConfig, this);
        user__deviceDao = new user__deviceDao(user__deviceDaoConfig, this);

        registerDao(UserDB.class, userDBDao);
        registerDao(DeviceDB.class, deviceDBDao);
        registerDao(user__device.class, user__deviceDao);
    }
    
    public void clear() {
        userDBDaoConfig.getIdentityScope().clear();
        deviceDBDaoConfig.getIdentityScope().clear();
        user__deviceDaoConfig.getIdentityScope().clear();
    }

    public UserDBDao getUserDBDao() {
        return userDBDao;
    }

    public DeviceDBDao getDeviceDBDao() {
        return deviceDBDao;
    }

    public user__deviceDao getUser__deviceDao() {
        return user__deviceDao;
    }

}
