package com.espressif.iot.db.greenrobot.daoDevice;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table DEVICE_DB.
 */
public class DeviceDB {

    private Long id;
    /** Not-null value. */
    private String bssid;
    /** Not-null value. */
    private String type;
    /** Not-null value. */
    private String status;

    public DeviceDB() {
    }

    public DeviceDB(Long id) {
        this.id = id;
    }

    public DeviceDB(Long id, String bssid, String type, String status) {
        this.id = id;
        this.bssid = bssid;
        this.type = type;
        this.status = status;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getBssid() {
        return bssid;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setBssid(String bssid) {
        this.bssid = bssid;
    }

    /** Not-null value. */
    public String getType() {
        return type;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setType(String type) {
        this.type = type;
    }

    /** Not-null value. */
    public String getStatus() {
        return status;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setStatus(String status) {
        this.status = status;
    }

}
