package com.espressif.iot.db.greenrobot.daoDevice;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table USER_DB.
 */
public class UserDB {

    private Long id;
    /** Not-null value. */
    private String key;

    public UserDB() {
    }

    public UserDB(Long id) {
        this.id = id;
    }

    public UserDB(Long id, String key) {
        this.id = id;
        this.key = key;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getKey() {
        return key;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setKey(String key) {
        this.key = key;
    }

}
